name: 101-startAppDesign

on:
  workflow_dispatch:
    inputs:
      DEV_BRANCH_NAME:
        required: true
        default: 'dev/001-first-development'
      FEATURE_BRANCH_NAME:
        required: true
        default: 'feature/app-design'
      COMMIT_MESSAGE:
        required: true
        default: 'Generated app design docs'
      MULE_APP_GROUP_ID:
        required: true
        default: 'jp.co.ctc.mulesoft'
      MULE_APP_VERSION:
        required: true
        default: '1.0.0-SNAPSHOT'

jobs:
  replace-appinfo-in-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      ########################################################################################################################
      # 1. Set environment
      ########################################################################################################################
      - name: Set environment on workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "DEV_BRANCH_NAME=${{ github.event.inputs.DEV_BRANCH_NAME }}" >> $GITHUB_ENV
          echo "FEATURE_BRANCH_NAME=${{ github.event.inputs.FEATURE_BRANCH_NAME }}" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=${{ github.event.inputs.COMMIT_MESSAGE }}" >> $GITHUB_ENV
          echo "MULE_APP_GROUP_ID=${{ github.event.inputs.MULE_APP_GROUP_ID }}" >> $GITHUB_ENV
          echo "MULE_APP_VERSION=${{ github.event.inputs.MULE_APP_VERSION }}" >> $GITHUB_ENV


      ########################################################################################################################
      # 2. Replace app info in docs
      ########################################################################################################################
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create dev branch and feature branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c ${{ env.DEV_BRANCH_NAME }}
          git push -u origin ${{ env.DEV_BRANCH_NAME }}
          git switch -c ${{ env.FEATURE_BRANCH_NAME }}
          git push -u origin ${{ env.FEATURE_BRANCH_NAME }}

      - name: Replace groupId in docs
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "${groupId}"
          replace: ${{ env.MULE_APP_GROUP_ID }}
          include: "docs/**"
          regex: false

      - name: Replace artifactId in docs
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "${artifactId}"
          replace: ${{ github.event.repository.name }}
          include: "docs/**"
          regex: false

      - name: Replace version info in docs
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "${version}"
          replace: ${{ env.MULE_APP_VERSION }}
          include: "docs/**"
          regex: false

      - name: Rename api spec file
        run: mv ./docs/apispec/apispecTemplate.raml ./docs/apispec/${{ github.event.repository.name }}.raml

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ env.FEATURE_BRANCH_NAME }}
          message: ${{ env.COMMIT_MESSAGE }}
          add: .
