name: 104-onDevBranch

on:
  pull_request:
    branches: dev/**
    types:
      - opened
      - closed    
    paths-ignore:
      - '.github/workflows/**'
      - '.gitignore'
      - '*.md'
      - 'docs/**'
      - 'src/main/resources/api/**'
      
  workflow_dispatch:

jobs:
  call-runMunitTestflow:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action == 'opened') || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/202-runMunitTest.yaml
    with:
      TARGET_TEST_SUITE: 'unit'

  call-deployToCloudHubflow:
    needs: call-runMunitTestflow
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    uses: ./.github/workflows/203-deployToCloudHub.yaml
    with:
      DEPLOY_TARGET_ENV: 'dev'
      DEPLOY_TARGET_ENV_NAME: 'commufa-dev-env'

